// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteWebhookParams creates a new DeleteWebhookParams object
// with the default values initialized.
func NewDeleteWebhookParams() *DeleteWebhookParams {
	var ()
	return &DeleteWebhookParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWebhookParamsWithTimeout creates a new DeleteWebhookParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteWebhookParamsWithTimeout(timeout time.Duration) *DeleteWebhookParams {
	var ()
	return &DeleteWebhookParams{

		timeout: timeout,
	}
}

// NewDeleteWebhookParamsWithContext creates a new DeleteWebhookParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteWebhookParamsWithContext(ctx context.Context) *DeleteWebhookParams {
	var ()
	return &DeleteWebhookParams{

		Context: ctx,
	}
}

// NewDeleteWebhookParamsWithHTTPClient creates a new DeleteWebhookParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteWebhookParamsWithHTTPClient(client *http.Client) *DeleteWebhookParams {
	var ()
	return &DeleteWebhookParams{
		HTTPClient: client,
	}
}

/*DeleteWebhookParams contains all the parameters to send to the API endpoint
for the delete webhook operation typically these are written to a http.Request
*/
type DeleteWebhookParams struct {

	/*ResourceID
	  The resource ID.

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete webhook params
func (o *DeleteWebhookParams) WithTimeout(timeout time.Duration) *DeleteWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete webhook params
func (o *DeleteWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete webhook params
func (o *DeleteWebhookParams) WithContext(ctx context.Context) *DeleteWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete webhook params
func (o *DeleteWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete webhook params
func (o *DeleteWebhookParams) WithHTTPClient(client *http.Client) *DeleteWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete webhook params
func (o *DeleteWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the delete webhook params
func (o *DeleteWebhookParams) WithResourceID(resourceID string) *DeleteWebhookParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the delete webhook params
func (o *DeleteWebhookParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
