// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/go-launchdarkly/models"
)

// GetWebhooksReader is a Reader for the GetWebhooks structure.
type GetWebhooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWebhooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWebhooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetWebhooksUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWebhooksOK creates a GetWebhooksOK with default headers values
func NewGetWebhooksOK() *GetWebhooksOK {
	return &GetWebhooksOK{}
}

/*GetWebhooksOK handles this case with default header values.

Webhooks response.
*/
type GetWebhooksOK struct {
	Payload *models.Webhooks
}

func (o *GetWebhooksOK) Error() string {
	return fmt.Sprintf("[GET /webhooks][%d] getWebhooksOK  %+v", 200, o.Payload)
}

func (o *GetWebhooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Webhooks)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWebhooksUnauthorized creates a GetWebhooksUnauthorized with default headers values
func NewGetWebhooksUnauthorized() *GetWebhooksUnauthorized {
	return &GetWebhooksUnauthorized{}
}

/*GetWebhooksUnauthorized handles this case with default header values.

Invalid access token.
*/
type GetWebhooksUnauthorized struct {
}

func (o *GetWebhooksUnauthorized) Error() string {
	return fmt.Sprintf("[GET /webhooks][%d] getWebhooksUnauthorized ", 401)
}

func (o *GetWebhooksUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
