// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWebhooksParams creates a new GetWebhooksParams object
// with the default values initialized.
func NewGetWebhooksParams() *GetWebhooksParams {

	return &GetWebhooksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWebhooksParamsWithTimeout creates a new GetWebhooksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWebhooksParamsWithTimeout(timeout time.Duration) *GetWebhooksParams {

	return &GetWebhooksParams{

		timeout: timeout,
	}
}

// NewGetWebhooksParamsWithContext creates a new GetWebhooksParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWebhooksParamsWithContext(ctx context.Context) *GetWebhooksParams {

	return &GetWebhooksParams{

		Context: ctx,
	}
}

// NewGetWebhooksParamsWithHTTPClient creates a new GetWebhooksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWebhooksParamsWithHTTPClient(client *http.Client) *GetWebhooksParams {

	return &GetWebhooksParams{
		HTTPClient: client,
	}
}

/*GetWebhooksParams contains all the parameters to send to the API endpoint
for the get webhooks operation typically these are written to a http.Request
*/
type GetWebhooksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get webhooks params
func (o *GetWebhooksParams) WithTimeout(timeout time.Duration) *GetWebhooksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get webhooks params
func (o *GetWebhooksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get webhooks params
func (o *GetWebhooksParams) WithContext(ctx context.Context) *GetWebhooksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get webhooks params
func (o *GetWebhooksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get webhooks params
func (o *GetWebhooksParams) WithHTTPClient(client *http.Client) *GetWebhooksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get webhooks params
func (o *GetWebhooksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetWebhooksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
