// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/go-launchdarkly/models"
)

// GetWebhookReader is a Reader for the GetWebhook structure.
type GetWebhookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWebhookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWebhookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetWebhookUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetWebhookNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWebhookOK creates a GetWebhookOK with default headers values
func NewGetWebhookOK() *GetWebhookOK {
	return &GetWebhookOK{}
}

/*GetWebhookOK handles this case with default header values.

Webhook response.
*/
type GetWebhookOK struct {
	Payload *models.Webhook
}

func (o *GetWebhookOK) Error() string {
	return fmt.Sprintf("[GET /webhooks/{resourceId}][%d] getWebhookOK  %+v", 200, o.Payload)
}

func (o *GetWebhookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Webhook)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWebhookUnauthorized creates a GetWebhookUnauthorized with default headers values
func NewGetWebhookUnauthorized() *GetWebhookUnauthorized {
	return &GetWebhookUnauthorized{}
}

/*GetWebhookUnauthorized handles this case with default header values.

Invalid access token.
*/
type GetWebhookUnauthorized struct {
}

func (o *GetWebhookUnauthorized) Error() string {
	return fmt.Sprintf("[GET /webhooks/{resourceId}][%d] getWebhookUnauthorized ", 401)
}

func (o *GetWebhookUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetWebhookNotFound creates a GetWebhookNotFound with default headers values
func NewGetWebhookNotFound() *GetWebhookNotFound {
	return &GetWebhookNotFound{}
}

/*GetWebhookNotFound handles this case with default header values.

Invalid resource specifier.
*/
type GetWebhookNotFound struct {
}

func (o *GetWebhookNotFound) Error() string {
	return fmt.Sprintf("[GET /webhooks/{resourceId}][%d] getWebhookNotFound ", 404)
}

func (o *GetWebhookNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
