// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostWebhookParams creates a new PostWebhookParams object
// with the default values initialized.
func NewPostWebhookParams() *PostWebhookParams {
	var ()
	return &PostWebhookParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostWebhookParamsWithTimeout creates a new PostWebhookParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostWebhookParamsWithTimeout(timeout time.Duration) *PostWebhookParams {
	var ()
	return &PostWebhookParams{

		timeout: timeout,
	}
}

// NewPostWebhookParamsWithContext creates a new PostWebhookParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostWebhookParamsWithContext(ctx context.Context) *PostWebhookParams {
	var ()
	return &PostWebhookParams{

		Context: ctx,
	}
}

// NewPostWebhookParamsWithHTTPClient creates a new PostWebhookParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostWebhookParamsWithHTTPClient(client *http.Client) *PostWebhookParams {
	var ()
	return &PostWebhookParams{
		HTTPClient: client,
	}
}

/*PostWebhookParams contains all the parameters to send to the API endpoint
for the post webhook operation typically these are written to a http.Request
*/
type PostWebhookParams struct {

	/*WebhookBody
	  New webhook.

	*/
	WebhookBody PostWebhookBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post webhook params
func (o *PostWebhookParams) WithTimeout(timeout time.Duration) *PostWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post webhook params
func (o *PostWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post webhook params
func (o *PostWebhookParams) WithContext(ctx context.Context) *PostWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post webhook params
func (o *PostWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post webhook params
func (o *PostWebhookParams) WithHTTPClient(client *http.Client) *PostWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post webhook params
func (o *PostWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWebhookBody adds the webhookBody to the post webhook params
func (o *PostWebhookParams) WithWebhookBody(webhookBody PostWebhookBody) *PostWebhookParams {
	o.SetWebhookBody(webhookBody)
	return o
}

// SetWebhookBody adds the webhookBody to the post webhook params
func (o *PostWebhookParams) SetWebhookBody(webhookBody PostWebhookBody) {
	o.WebhookBody = webhookBody
}

// WriteToRequest writes these params to a swagger request
func (o *PostWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.WebhookBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
