// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new webhooks API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for webhooks API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DeleteWebhook deletes a webhook by ID
*/
func (a *Client) DeleteWebhook(params *DeleteWebhookParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteWebhookNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteWebhookParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteWebhook",
		Method:             "DELETE",
		PathPattern:        "/webhooks/{resourceId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteWebhookNoContent), nil

}

/*
GetWebhook gets a webhook by ID
*/
func (a *Client) GetWebhook(params *GetWebhookParams, authInfo runtime.ClientAuthInfoWriter) (*GetWebhookOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetWebhookParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getWebhook",
		Method:             "GET",
		PathPattern:        "/webhooks/{resourceId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetWebhookOK), nil

}

/*
GetWebhooks fetches a list of all webhooks
*/
func (a *Client) GetWebhooks(params *GetWebhooksParams, authInfo runtime.ClientAuthInfoWriter) (*GetWebhooksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetWebhooksParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getWebhooks",
		Method:             "GET",
		PathPattern:        "/webhooks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetWebhooksReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetWebhooksOK), nil

}

/*
PatchWebhook modifies a webhook by ID
*/
func (a *Client) PatchWebhook(params *PatchWebhookParams, authInfo runtime.ClientAuthInfoWriter) (*PatchWebhookOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchWebhookParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patchWebhook",
		Method:             "PATCH",
		PathPattern:        "/webhooks/{resourceId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PatchWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PatchWebhookOK), nil

}

/*
PostWebhook creates a webhook
*/
func (a *Client) PostWebhook(params *PostWebhookParams, authInfo runtime.ClientAuthInfoWriter) (*PostWebhookCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostWebhookParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postWebhook",
		Method:             "POST",
		PathPattern:        "/webhooks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostWebhookReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostWebhookCreated), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
