// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/launchdarkly-api-client/models"
)

// NewPatchProjectParams creates a new PatchProjectParams object
// with the default values initialized.
func NewPatchProjectParams() *PatchProjectParams {
	var ()
	return &PatchProjectParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchProjectParamsWithTimeout creates a new PatchProjectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchProjectParamsWithTimeout(timeout time.Duration) *PatchProjectParams {
	var ()
	return &PatchProjectParams{

		timeout: timeout,
	}
}

// NewPatchProjectParamsWithContext creates a new PatchProjectParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchProjectParamsWithContext(ctx context.Context) *PatchProjectParams {
	var ()
	return &PatchProjectParams{

		Context: ctx,
	}
}

// NewPatchProjectParamsWithHTTPClient creates a new PatchProjectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchProjectParamsWithHTTPClient(client *http.Client) *PatchProjectParams {
	var ()
	return &PatchProjectParams{
		HTTPClient: client,
	}
}

/*PatchProjectParams contains all the parameters to send to the API endpoint
for the patch project operation typically these are written to a http.Request
*/
type PatchProjectParams struct {

	/*PatchDelta
	  Requires a JSON Patch representation of the desired changes to the project. 'http://jsonpatch.com/'

	*/
	PatchDelta []*models.PatchOperation
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch project params
func (o *PatchProjectParams) WithTimeout(timeout time.Duration) *PatchProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch project params
func (o *PatchProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch project params
func (o *PatchProjectParams) WithContext(ctx context.Context) *PatchProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch project params
func (o *PatchProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch project params
func (o *PatchProjectParams) WithHTTPClient(client *http.Client) *PatchProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch project params
func (o *PatchProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPatchDelta adds the patchDelta to the patch project params
func (o *PatchProjectParams) WithPatchDelta(patchDelta []*models.PatchOperation) *PatchProjectParams {
	o.SetPatchDelta(patchDelta)
	return o
}

// SetPatchDelta adds the patchDelta to the patch project params
func (o *PatchProjectParams) SetPatchDelta(patchDelta []*models.PatchOperation) {
	o.PatchDelta = patchDelta
}

// WithProjectKey adds the projectKey to the patch project params
func (o *PatchProjectParams) WithProjectKey(projectKey string) *PatchProjectParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the patch project params
func (o *PatchProjectParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WriteToRequest writes these params to a swagger request
func (o *PatchProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PatchDelta != nil {
		if err := r.SetBodyParam(o.PatchDelta); err != nil {
			return err
		}
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
