// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFeatureFlagStatusParams creates a new GetFeatureFlagStatusParams object
// with the default values initialized.
func NewGetFeatureFlagStatusParams() *GetFeatureFlagStatusParams {
	var ()
	return &GetFeatureFlagStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFeatureFlagStatusParamsWithTimeout creates a new GetFeatureFlagStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFeatureFlagStatusParamsWithTimeout(timeout time.Duration) *GetFeatureFlagStatusParams {
	var ()
	return &GetFeatureFlagStatusParams{

		timeout: timeout,
	}
}

// NewGetFeatureFlagStatusParamsWithContext creates a new GetFeatureFlagStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFeatureFlagStatusParamsWithContext(ctx context.Context) *GetFeatureFlagStatusParams {
	var ()
	return &GetFeatureFlagStatusParams{

		Context: ctx,
	}
}

// NewGetFeatureFlagStatusParamsWithHTTPClient creates a new GetFeatureFlagStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFeatureFlagStatusParamsWithHTTPClient(client *http.Client) *GetFeatureFlagStatusParams {
	var ()
	return &GetFeatureFlagStatusParams{
		HTTPClient: client,
	}
}

/*GetFeatureFlagStatusParams contains all the parameters to send to the API endpoint
for the get feature flag status operation typically these are written to a http.Request
*/
type GetFeatureFlagStatusParams struct {

	/*EnvironmentKey
	  The environment key, used to tie together flag configuration and users under one environment so they can be managed together.

	*/
	EnvironmentKey string
	/*FeatureFlagKey
	  The feature flag's key. The key identifies the flag in your code.

	*/
	FeatureFlagKey string
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get feature flag status params
func (o *GetFeatureFlagStatusParams) WithTimeout(timeout time.Duration) *GetFeatureFlagStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get feature flag status params
func (o *GetFeatureFlagStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get feature flag status params
func (o *GetFeatureFlagStatusParams) WithContext(ctx context.Context) *GetFeatureFlagStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get feature flag status params
func (o *GetFeatureFlagStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get feature flag status params
func (o *GetFeatureFlagStatusParams) WithHTTPClient(client *http.Client) *GetFeatureFlagStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get feature flag status params
func (o *GetFeatureFlagStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentKey adds the environmentKey to the get feature flag status params
func (o *GetFeatureFlagStatusParams) WithEnvironmentKey(environmentKey string) *GetFeatureFlagStatusParams {
	o.SetEnvironmentKey(environmentKey)
	return o
}

// SetEnvironmentKey adds the environmentKey to the get feature flag status params
func (o *GetFeatureFlagStatusParams) SetEnvironmentKey(environmentKey string) {
	o.EnvironmentKey = environmentKey
}

// WithFeatureFlagKey adds the featureFlagKey to the get feature flag status params
func (o *GetFeatureFlagStatusParams) WithFeatureFlagKey(featureFlagKey string) *GetFeatureFlagStatusParams {
	o.SetFeatureFlagKey(featureFlagKey)
	return o
}

// SetFeatureFlagKey adds the featureFlagKey to the get feature flag status params
func (o *GetFeatureFlagStatusParams) SetFeatureFlagKey(featureFlagKey string) {
	o.FeatureFlagKey = featureFlagKey
}

// WithProjectKey adds the projectKey to the get feature flag status params
func (o *GetFeatureFlagStatusParams) WithProjectKey(projectKey string) *GetFeatureFlagStatusParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the get feature flag status params
func (o *GetFeatureFlagStatusParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WriteToRequest writes these params to a swagger request
func (o *GetFeatureFlagStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentKey
	if err := r.SetPathParam("environmentKey", o.EnvironmentKey); err != nil {
		return err
	}

	// path param featureFlagKey
	if err := r.SetPathParam("featureFlagKey", o.FeatureFlagKey); err != nil {
		return err
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
