// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/go-launchdarkly/models"
)

// GetFeatureFlagStatusesReader is a Reader for the GetFeatureFlagStatuses structure.
type GetFeatureFlagStatusesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFeatureFlagStatusesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetFeatureFlagStatusesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetFeatureFlagStatusesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetFeatureFlagStatusesOK creates a GetFeatureFlagStatusesOK with default headers values
func NewGetFeatureFlagStatusesOK() *GetFeatureFlagStatusesOK {
	return &GetFeatureFlagStatusesOK{}
}

/*GetFeatureFlagStatusesOK handles this case with default header values.

List of feature flag statuses.
*/
type GetFeatureFlagStatusesOK struct {
	Payload *models.FeatureFlagStatuses
}

func (o *GetFeatureFlagStatusesOK) Error() string {
	return fmt.Sprintf("[GET /flag-statuses/{projectKey}/{environmentKey}][%d] getFeatureFlagStatusesOK  %+v", 200, o.Payload)
}

func (o *GetFeatureFlagStatusesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FeatureFlagStatuses)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFeatureFlagStatusesUnauthorized creates a GetFeatureFlagStatusesUnauthorized with default headers values
func NewGetFeatureFlagStatusesUnauthorized() *GetFeatureFlagStatusesUnauthorized {
	return &GetFeatureFlagStatusesUnauthorized{}
}

/*GetFeatureFlagStatusesUnauthorized handles this case with default header values.

Invalid access token.
*/
type GetFeatureFlagStatusesUnauthorized struct {
}

func (o *GetFeatureFlagStatusesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /flag-statuses/{projectKey}/{environmentKey}][%d] getFeatureFlagStatusesUnauthorized ", 401)
}

func (o *GetFeatureFlagStatusesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
