// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFeatureFlagStatusesParams creates a new GetFeatureFlagStatusesParams object
// with the default values initialized.
func NewGetFeatureFlagStatusesParams() *GetFeatureFlagStatusesParams {
	var ()
	return &GetFeatureFlagStatusesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFeatureFlagStatusesParamsWithTimeout creates a new GetFeatureFlagStatusesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFeatureFlagStatusesParamsWithTimeout(timeout time.Duration) *GetFeatureFlagStatusesParams {
	var ()
	return &GetFeatureFlagStatusesParams{

		timeout: timeout,
	}
}

// NewGetFeatureFlagStatusesParamsWithContext creates a new GetFeatureFlagStatusesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFeatureFlagStatusesParamsWithContext(ctx context.Context) *GetFeatureFlagStatusesParams {
	var ()
	return &GetFeatureFlagStatusesParams{

		Context: ctx,
	}
}

// NewGetFeatureFlagStatusesParamsWithHTTPClient creates a new GetFeatureFlagStatusesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFeatureFlagStatusesParamsWithHTTPClient(client *http.Client) *GetFeatureFlagStatusesParams {
	var ()
	return &GetFeatureFlagStatusesParams{
		HTTPClient: client,
	}
}

/*GetFeatureFlagStatusesParams contains all the parameters to send to the API endpoint
for the get feature flag statuses operation typically these are written to a http.Request
*/
type GetFeatureFlagStatusesParams struct {

	/*EnvironmentKey
	  The environment key, used to tie together flag configuration and users under one environment so they can be managed together.

	*/
	EnvironmentKey string
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) WithTimeout(timeout time.Duration) *GetFeatureFlagStatusesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) WithContext(ctx context.Context) *GetFeatureFlagStatusesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) WithHTTPClient(client *http.Client) *GetFeatureFlagStatusesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentKey adds the environmentKey to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) WithEnvironmentKey(environmentKey string) *GetFeatureFlagStatusesParams {
	o.SetEnvironmentKey(environmentKey)
	return o
}

// SetEnvironmentKey adds the environmentKey to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) SetEnvironmentKey(environmentKey string) {
	o.EnvironmentKey = environmentKey
}

// WithProjectKey adds the projectKey to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) WithProjectKey(projectKey string) *GetFeatureFlagStatusesParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the get feature flag statuses params
func (o *GetFeatureFlagStatusesParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WriteToRequest writes these params to a swagger request
func (o *GetFeatureFlagStatusesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentKey
	if err := r.SetPathParam("environmentKey", o.EnvironmentKey); err != nil {
		return err
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
