// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/launchdarkly-api-client/models"
)

// GetFeatureFlagStatusReader is a Reader for the GetFeatureFlagStatus structure.
type GetFeatureFlagStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFeatureFlagStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetFeatureFlagStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetFeatureFlagStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetFeatureFlagStatusOK creates a GetFeatureFlagStatusOK with default headers values
func NewGetFeatureFlagStatusOK() *GetFeatureFlagStatusOK {
	return &GetFeatureFlagStatusOK{}
}

/*GetFeatureFlagStatusOK handles this case with default header values.

Status of the requested feature flag.
*/
type GetFeatureFlagStatusOK struct {
	Payload *models.FeatureFlagStatus
}

func (o *GetFeatureFlagStatusOK) Error() string {
	return fmt.Sprintf("[GET /flag-statuses/{projectKey}/{environmentKey}/{featureFlagKey}][%d] getFeatureFlagStatusOK  %+v", 200, o.Payload)
}

func (o *GetFeatureFlagStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FeatureFlagStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFeatureFlagStatusUnauthorized creates a GetFeatureFlagStatusUnauthorized with default headers values
func NewGetFeatureFlagStatusUnauthorized() *GetFeatureFlagStatusUnauthorized {
	return &GetFeatureFlagStatusUnauthorized{}
}

/*GetFeatureFlagStatusUnauthorized handles this case with default header values.

Invalid access token.
*/
type GetFeatureFlagStatusUnauthorized struct {
}

func (o *GetFeatureFlagStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /flag-statuses/{projectKey}/{environmentKey}/{featureFlagKey}][%d] getFeatureFlagStatusUnauthorized ", 401)
}

func (o *GetFeatureFlagStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
