// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFeatureFlagParams creates a new GetFeatureFlagParams object
// with the default values initialized.
func NewGetFeatureFlagParams() *GetFeatureFlagParams {
	var ()
	return &GetFeatureFlagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFeatureFlagParamsWithTimeout creates a new GetFeatureFlagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFeatureFlagParamsWithTimeout(timeout time.Duration) *GetFeatureFlagParams {
	var ()
	return &GetFeatureFlagParams{

		timeout: timeout,
	}
}

// NewGetFeatureFlagParamsWithContext creates a new GetFeatureFlagParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFeatureFlagParamsWithContext(ctx context.Context) *GetFeatureFlagParams {
	var ()
	return &GetFeatureFlagParams{

		Context: ctx,
	}
}

// NewGetFeatureFlagParamsWithHTTPClient creates a new GetFeatureFlagParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFeatureFlagParamsWithHTTPClient(client *http.Client) *GetFeatureFlagParams {
	var ()
	return &GetFeatureFlagParams{
		HTTPClient: client,
	}
}

/*GetFeatureFlagParams contains all the parameters to send to the API endpoint
for the get feature flag operation typically these are written to a http.Request
*/
type GetFeatureFlagParams struct {

	/*Env
	  By default, each feature will include configurations for each environment. You can filter environments with the env query parameter. For example, setting env=production will restrict the returned configurations to just your production environment.

	*/
	Env *string
	/*FeatureFlagKey
	  The feature flag's key. The key identifies the flag in your code.

	*/
	FeatureFlagKey string
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get feature flag params
func (o *GetFeatureFlagParams) WithTimeout(timeout time.Duration) *GetFeatureFlagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get feature flag params
func (o *GetFeatureFlagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get feature flag params
func (o *GetFeatureFlagParams) WithContext(ctx context.Context) *GetFeatureFlagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get feature flag params
func (o *GetFeatureFlagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get feature flag params
func (o *GetFeatureFlagParams) WithHTTPClient(client *http.Client) *GetFeatureFlagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get feature flag params
func (o *GetFeatureFlagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnv adds the env to the get feature flag params
func (o *GetFeatureFlagParams) WithEnv(env *string) *GetFeatureFlagParams {
	o.SetEnv(env)
	return o
}

// SetEnv adds the env to the get feature flag params
func (o *GetFeatureFlagParams) SetEnv(env *string) {
	o.Env = env
}

// WithFeatureFlagKey adds the featureFlagKey to the get feature flag params
func (o *GetFeatureFlagParams) WithFeatureFlagKey(featureFlagKey string) *GetFeatureFlagParams {
	o.SetFeatureFlagKey(featureFlagKey)
	return o
}

// SetFeatureFlagKey adds the featureFlagKey to the get feature flag params
func (o *GetFeatureFlagParams) SetFeatureFlagKey(featureFlagKey string) {
	o.FeatureFlagKey = featureFlagKey
}

// WithProjectKey adds the projectKey to the get feature flag params
func (o *GetFeatureFlagParams) WithProjectKey(projectKey string) *GetFeatureFlagParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the get feature flag params
func (o *GetFeatureFlagParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WriteToRequest writes these params to a swagger request
func (o *GetFeatureFlagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Env != nil {

		// query param env
		var qrEnv string
		if o.Env != nil {
			qrEnv = *o.Env
		}
		qEnv := qrEnv
		if qEnv != "" {
			if err := r.SetQueryParam("env", qEnv); err != nil {
				return err
			}
		}

	}

	// path param featureFlagKey
	if err := r.SetPathParam("featureFlagKey", o.FeatureFlagKey); err != nil {
		return err
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
