// Code generated by go-swagger; DO NOT EDIT.

package feature_flags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPatchFeatureFlagParams creates a new PatchFeatureFlagParams object
// with the default values initialized.
func NewPatchFeatureFlagParams() *PatchFeatureFlagParams {
	var ()
	return &PatchFeatureFlagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchFeatureFlagParamsWithTimeout creates a new PatchFeatureFlagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchFeatureFlagParamsWithTimeout(timeout time.Duration) *PatchFeatureFlagParams {
	var ()
	return &PatchFeatureFlagParams{

		timeout: timeout,
	}
}

// NewPatchFeatureFlagParamsWithContext creates a new PatchFeatureFlagParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchFeatureFlagParamsWithContext(ctx context.Context) *PatchFeatureFlagParams {
	var ()
	return &PatchFeatureFlagParams{

		Context: ctx,
	}
}

// NewPatchFeatureFlagParamsWithHTTPClient creates a new PatchFeatureFlagParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchFeatureFlagParamsWithHTTPClient(client *http.Client) *PatchFeatureFlagParams {
	var ()
	return &PatchFeatureFlagParams{
		HTTPClient: client,
	}
}

/*PatchFeatureFlagParams contains all the parameters to send to the API endpoint
for the patch feature flag operation typically these are written to a http.Request
*/
type PatchFeatureFlagParams struct {

	/*FeatureFlagKey
	  The feature flag's key. The key identifies the flag in your code.

	*/
	FeatureFlagKey string
	/*PatchComment
	  Requires a JSON Patch representation of the desired changes to the project, and an optional comment. 'http://jsonpatch.com/' Feature flag patches also support JSON Merge Patch format. 'https://tools.ietf.org/html/rfc7386' The addition of comments is also supported.

	*/
	PatchComment PatchFeatureFlagBody
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch feature flag params
func (o *PatchFeatureFlagParams) WithTimeout(timeout time.Duration) *PatchFeatureFlagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch feature flag params
func (o *PatchFeatureFlagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch feature flag params
func (o *PatchFeatureFlagParams) WithContext(ctx context.Context) *PatchFeatureFlagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch feature flag params
func (o *PatchFeatureFlagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch feature flag params
func (o *PatchFeatureFlagParams) WithHTTPClient(client *http.Client) *PatchFeatureFlagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch feature flag params
func (o *PatchFeatureFlagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFeatureFlagKey adds the featureFlagKey to the patch feature flag params
func (o *PatchFeatureFlagParams) WithFeatureFlagKey(featureFlagKey string) *PatchFeatureFlagParams {
	o.SetFeatureFlagKey(featureFlagKey)
	return o
}

// SetFeatureFlagKey adds the featureFlagKey to the patch feature flag params
func (o *PatchFeatureFlagParams) SetFeatureFlagKey(featureFlagKey string) {
	o.FeatureFlagKey = featureFlagKey
}

// WithPatchComment adds the patchComment to the patch feature flag params
func (o *PatchFeatureFlagParams) WithPatchComment(patchComment PatchFeatureFlagBody) *PatchFeatureFlagParams {
	o.SetPatchComment(patchComment)
	return o
}

// SetPatchComment adds the patchComment to the patch feature flag params
func (o *PatchFeatureFlagParams) SetPatchComment(patchComment PatchFeatureFlagBody) {
	o.PatchComment = patchComment
}

// WithProjectKey adds the projectKey to the patch feature flag params
func (o *PatchFeatureFlagParams) WithProjectKey(projectKey string) *PatchFeatureFlagParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the patch feature flag params
func (o *PatchFeatureFlagParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WriteToRequest writes these params to a swagger request
func (o *PatchFeatureFlagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param featureFlagKey
	if err := r.SetPathParam("featureFlagKey", o.FeatureFlagKey); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.PatchComment); err != nil {
		return err
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
