// Code generated by go-swagger; DO NOT EDIT.

package user_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserFlagSettingsParams creates a new GetUserFlagSettingsParams object
// with the default values initialized.
func NewGetUserFlagSettingsParams() *GetUserFlagSettingsParams {
	var ()
	return &GetUserFlagSettingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserFlagSettingsParamsWithTimeout creates a new GetUserFlagSettingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserFlagSettingsParamsWithTimeout(timeout time.Duration) *GetUserFlagSettingsParams {
	var ()
	return &GetUserFlagSettingsParams{

		timeout: timeout,
	}
}

// NewGetUserFlagSettingsParamsWithContext creates a new GetUserFlagSettingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserFlagSettingsParamsWithContext(ctx context.Context) *GetUserFlagSettingsParams {
	var ()
	return &GetUserFlagSettingsParams{

		Context: ctx,
	}
}

// NewGetUserFlagSettingsParamsWithHTTPClient creates a new GetUserFlagSettingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserFlagSettingsParamsWithHTTPClient(client *http.Client) *GetUserFlagSettingsParams {
	var ()
	return &GetUserFlagSettingsParams{
		HTTPClient: client,
	}
}

/*GetUserFlagSettingsParams contains all the parameters to send to the API endpoint
for the get user flag settings operation typically these are written to a http.Request
*/
type GetUserFlagSettingsParams struct {

	/*EnvironmentKey
	  The environment key, used to tie together flag configuration and users under one environment so they can be managed together.

	*/
	EnvironmentKey string
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string
	/*UserKey
	  The user's key.

	*/
	UserKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user flag settings params
func (o *GetUserFlagSettingsParams) WithTimeout(timeout time.Duration) *GetUserFlagSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user flag settings params
func (o *GetUserFlagSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user flag settings params
func (o *GetUserFlagSettingsParams) WithContext(ctx context.Context) *GetUserFlagSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user flag settings params
func (o *GetUserFlagSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user flag settings params
func (o *GetUserFlagSettingsParams) WithHTTPClient(client *http.Client) *GetUserFlagSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user flag settings params
func (o *GetUserFlagSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentKey adds the environmentKey to the get user flag settings params
func (o *GetUserFlagSettingsParams) WithEnvironmentKey(environmentKey string) *GetUserFlagSettingsParams {
	o.SetEnvironmentKey(environmentKey)
	return o
}

// SetEnvironmentKey adds the environmentKey to the get user flag settings params
func (o *GetUserFlagSettingsParams) SetEnvironmentKey(environmentKey string) {
	o.EnvironmentKey = environmentKey
}

// WithProjectKey adds the projectKey to the get user flag settings params
func (o *GetUserFlagSettingsParams) WithProjectKey(projectKey string) *GetUserFlagSettingsParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the get user flag settings params
func (o *GetUserFlagSettingsParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WithUserKey adds the userKey to the get user flag settings params
func (o *GetUserFlagSettingsParams) WithUserKey(userKey string) *GetUserFlagSettingsParams {
	o.SetUserKey(userKey)
	return o
}

// SetUserKey adds the userKey to the get user flag settings params
func (o *GetUserFlagSettingsParams) SetUserKey(userKey string) {
	o.UserKey = userKey
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserFlagSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentKey
	if err := r.SetPathParam("environmentKey", o.EnvironmentKey); err != nil {
		return err
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	// path param userKey
	if err := r.SetPathParam("userKey", o.UserKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
