// Code generated by go-swagger; DO NOT EDIT.

package user_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new user settings API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for user settings API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetUserFlagSetting fetches a single flag setting for a user by key
*/
func (a *Client) GetUserFlagSetting(params *GetUserFlagSettingParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserFlagSettingOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserFlagSettingParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUserFlagSetting",
		Method:             "GET",
		PathPattern:        "/users/{projectKey}/{environmentKey}/{userKey}/flags/{featureFlagKey}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetUserFlagSettingReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetUserFlagSettingOK), nil

}

/*
GetUserFlagSettings fetches a single flag setting for a user by key
*/
func (a *Client) GetUserFlagSettings(params *GetUserFlagSettingsParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserFlagSettingsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserFlagSettingsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUserFlagSettings",
		Method:             "GET",
		PathPattern:        "/users/{projectKey}/{environmentKey}/{userKey}/flags",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetUserFlagSettingsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetUserFlagSettingsOK), nil

}

/*
PutFlagSetting specificallies enable or disable a feature flag for a user based on their key
*/
func (a *Client) PutFlagSetting(params *PutFlagSettingParams, authInfo runtime.ClientAuthInfoWriter) (*PutFlagSettingNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutFlagSettingParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "putFlagSetting",
		Method:             "PUT",
		PathPattern:        "/users/{projectKey}/{environmentKey}/{userKey}/flags/{featureFlagKey}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutFlagSettingReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PutFlagSettingNoContent), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
