// Code generated by go-swagger; DO NOT EDIT.

package user_segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/go-launchdarkly/models"
)

// GetUserSegmentsReader is a Reader for the GetUserSegments structure.
type GetUserSegmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserSegmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUserSegmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetUserSegmentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUserSegmentsOK creates a GetUserSegmentsOK with default headers values
func NewGetUserSegmentsOK() *GetUserSegmentsOK {
	return &GetUserSegmentsOK{}
}

/*GetUserSegmentsOK handles this case with default header values.

Segments response.
*/
type GetUserSegmentsOK struct {
	Payload *models.UserSegments
}

func (o *GetUserSegmentsOK) Error() string {
	return fmt.Sprintf("[GET /segments/{projectKey}/{environmentKey}][%d] getUserSegmentsOK  %+v", 200, o.Payload)
}

func (o *GetUserSegmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserSegments)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserSegmentsUnauthorized creates a GetUserSegmentsUnauthorized with default headers values
func NewGetUserSegmentsUnauthorized() *GetUserSegmentsUnauthorized {
	return &GetUserSegmentsUnauthorized{}
}

/*GetUserSegmentsUnauthorized handles this case with default header values.

Invalid access token.
*/
type GetUserSegmentsUnauthorized struct {
}

func (o *GetUserSegmentsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /segments/{projectKey}/{environmentKey}][%d] getUserSegmentsUnauthorized ", 401)
}

func (o *GetUserSegmentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
