// Code generated by go-swagger; DO NOT EDIT.

package user_segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserSegmentsParams creates a new GetUserSegmentsParams object
// with the default values initialized.
func NewGetUserSegmentsParams() *GetUserSegmentsParams {
	var ()
	return &GetUserSegmentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserSegmentsParamsWithTimeout creates a new GetUserSegmentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserSegmentsParamsWithTimeout(timeout time.Duration) *GetUserSegmentsParams {
	var ()
	return &GetUserSegmentsParams{

		timeout: timeout,
	}
}

// NewGetUserSegmentsParamsWithContext creates a new GetUserSegmentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserSegmentsParamsWithContext(ctx context.Context) *GetUserSegmentsParams {
	var ()
	return &GetUserSegmentsParams{

		Context: ctx,
	}
}

// NewGetUserSegmentsParamsWithHTTPClient creates a new GetUserSegmentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserSegmentsParamsWithHTTPClient(client *http.Client) *GetUserSegmentsParams {
	var ()
	return &GetUserSegmentsParams{
		HTTPClient: client,
	}
}

/*GetUserSegmentsParams contains all the parameters to send to the API endpoint
for the get user segments operation typically these are written to a http.Request
*/
type GetUserSegmentsParams struct {

	/*EnvironmentKey
	  The environment key, used to tie together flag configuration and users under one environment so they can be managed together.

	*/
	EnvironmentKey string
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string
	/*Tag
	  Filter by tag. A tag can be used to group flags across projects.

	*/
	Tag *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user segments params
func (o *GetUserSegmentsParams) WithTimeout(timeout time.Duration) *GetUserSegmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user segments params
func (o *GetUserSegmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user segments params
func (o *GetUserSegmentsParams) WithContext(ctx context.Context) *GetUserSegmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user segments params
func (o *GetUserSegmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user segments params
func (o *GetUserSegmentsParams) WithHTTPClient(client *http.Client) *GetUserSegmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user segments params
func (o *GetUserSegmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentKey adds the environmentKey to the get user segments params
func (o *GetUserSegmentsParams) WithEnvironmentKey(environmentKey string) *GetUserSegmentsParams {
	o.SetEnvironmentKey(environmentKey)
	return o
}

// SetEnvironmentKey adds the environmentKey to the get user segments params
func (o *GetUserSegmentsParams) SetEnvironmentKey(environmentKey string) {
	o.EnvironmentKey = environmentKey
}

// WithProjectKey adds the projectKey to the get user segments params
func (o *GetUserSegmentsParams) WithProjectKey(projectKey string) *GetUserSegmentsParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the get user segments params
func (o *GetUserSegmentsParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WithTag adds the tag to the get user segments params
func (o *GetUserSegmentsParams) WithTag(tag *string) *GetUserSegmentsParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get user segments params
func (o *GetUserSegmentsParams) SetTag(tag *string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserSegmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentKey
	if err := r.SetPathParam("environmentKey", o.EnvironmentKey); err != nil {
		return err
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	if o.Tag != nil {

		// query param tag
		var qrTag string
		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {
			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
