// Code generated by go-swagger; DO NOT EDIT.

package user_segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostUserSegmentParams creates a new PostUserSegmentParams object
// with the default values initialized.
func NewPostUserSegmentParams() *PostUserSegmentParams {
	var ()
	return &PostUserSegmentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostUserSegmentParamsWithTimeout creates a new PostUserSegmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostUserSegmentParamsWithTimeout(timeout time.Duration) *PostUserSegmentParams {
	var ()
	return &PostUserSegmentParams{

		timeout: timeout,
	}
}

// NewPostUserSegmentParamsWithContext creates a new PostUserSegmentParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostUserSegmentParamsWithContext(ctx context.Context) *PostUserSegmentParams {
	var ()
	return &PostUserSegmentParams{

		Context: ctx,
	}
}

// NewPostUserSegmentParamsWithHTTPClient creates a new PostUserSegmentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostUserSegmentParamsWithHTTPClient(client *http.Client) *PostUserSegmentParams {
	var ()
	return &PostUserSegmentParams{
		HTTPClient: client,
	}
}

/*PostUserSegmentParams contains all the parameters to send to the API endpoint
for the post user segment operation typically these are written to a http.Request
*/
type PostUserSegmentParams struct {

	/*EnvironmentKey
	  The environment key, used to tie together flag configuration and users under one environment so they can be managed together.

	*/
	EnvironmentKey string
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string
	/*UserSegmentBody
	  Create a new user segment.

	*/
	UserSegmentBody PostUserSegmentBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post user segment params
func (o *PostUserSegmentParams) WithTimeout(timeout time.Duration) *PostUserSegmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post user segment params
func (o *PostUserSegmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post user segment params
func (o *PostUserSegmentParams) WithContext(ctx context.Context) *PostUserSegmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post user segment params
func (o *PostUserSegmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post user segment params
func (o *PostUserSegmentParams) WithHTTPClient(client *http.Client) *PostUserSegmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post user segment params
func (o *PostUserSegmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentKey adds the environmentKey to the post user segment params
func (o *PostUserSegmentParams) WithEnvironmentKey(environmentKey string) *PostUserSegmentParams {
	o.SetEnvironmentKey(environmentKey)
	return o
}

// SetEnvironmentKey adds the environmentKey to the post user segment params
func (o *PostUserSegmentParams) SetEnvironmentKey(environmentKey string) {
	o.EnvironmentKey = environmentKey
}

// WithProjectKey adds the projectKey to the post user segment params
func (o *PostUserSegmentParams) WithProjectKey(projectKey string) *PostUserSegmentParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the post user segment params
func (o *PostUserSegmentParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WithUserSegmentBody adds the userSegmentBody to the post user segment params
func (o *PostUserSegmentParams) WithUserSegmentBody(userSegmentBody PostUserSegmentBody) *PostUserSegmentParams {
	o.SetUserSegmentBody(userSegmentBody)
	return o
}

// SetUserSegmentBody adds the userSegmentBody to the post user segment params
func (o *PostUserSegmentParams) SetUserSegmentBody(userSegmentBody PostUserSegmentBody) {
	o.UserSegmentBody = userSegmentBody
}

// WriteToRequest writes these params to a swagger request
func (o *PostUserSegmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentKey
	if err := r.SetPathParam("environmentKey", o.EnvironmentKey); err != nil {
		return err
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.UserSegmentBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
