// Code generated by go-swagger; DO NOT EDIT.

package custom_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCustomRoleParams creates a new DeleteCustomRoleParams object
// with the default values initialized.
func NewDeleteCustomRoleParams() *DeleteCustomRoleParams {
	var ()
	return &DeleteCustomRoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCustomRoleParamsWithTimeout creates a new DeleteCustomRoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCustomRoleParamsWithTimeout(timeout time.Duration) *DeleteCustomRoleParams {
	var ()
	return &DeleteCustomRoleParams{

		timeout: timeout,
	}
}

// NewDeleteCustomRoleParamsWithContext creates a new DeleteCustomRoleParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCustomRoleParamsWithContext(ctx context.Context) *DeleteCustomRoleParams {
	var ()
	return &DeleteCustomRoleParams{

		Context: ctx,
	}
}

// NewDeleteCustomRoleParamsWithHTTPClient creates a new DeleteCustomRoleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCustomRoleParamsWithHTTPClient(client *http.Client) *DeleteCustomRoleParams {
	var ()
	return &DeleteCustomRoleParams{
		HTTPClient: client,
	}
}

/*DeleteCustomRoleParams contains all the parameters to send to the API endpoint
for the delete custom role operation typically these are written to a http.Request
*/
type DeleteCustomRoleParams struct {

	/*CustomRoleKey
	  The custom role key.

	*/
	CustomRoleKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete custom role params
func (o *DeleteCustomRoleParams) WithTimeout(timeout time.Duration) *DeleteCustomRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete custom role params
func (o *DeleteCustomRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete custom role params
func (o *DeleteCustomRoleParams) WithContext(ctx context.Context) *DeleteCustomRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete custom role params
func (o *DeleteCustomRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete custom role params
func (o *DeleteCustomRoleParams) WithHTTPClient(client *http.Client) *DeleteCustomRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete custom role params
func (o *DeleteCustomRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomRoleKey adds the customRoleKey to the delete custom role params
func (o *DeleteCustomRoleParams) WithCustomRoleKey(customRoleKey string) *DeleteCustomRoleParams {
	o.SetCustomRoleKey(customRoleKey)
	return o
}

// SetCustomRoleKey adds the customRoleKey to the delete custom role params
func (o *DeleteCustomRoleParams) SetCustomRoleKey(customRoleKey string) {
	o.CustomRoleKey = customRoleKey
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCustomRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customRoleKey
	if err := r.SetPathParam("customRoleKey", o.CustomRoleKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
