// Code generated by go-swagger; DO NOT EDIT.

package custom_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteCustomRoleReader is a Reader for the DeleteCustomRole structure.
type DeleteCustomRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCustomRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteCustomRoleNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteCustomRoleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteCustomRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCustomRoleNoContent creates a DeleteCustomRoleNoContent with default headers values
func NewDeleteCustomRoleNoContent() *DeleteCustomRoleNoContent {
	return &DeleteCustomRoleNoContent{}
}

/*DeleteCustomRoleNoContent handles this case with default header values.

Action completed successfully.
*/
type DeleteCustomRoleNoContent struct {
}

func (o *DeleteCustomRoleNoContent) Error() string {
	return fmt.Sprintf("[DELETE /roles/{customRoleKey}][%d] deleteCustomRoleNoContent ", 204)
}

func (o *DeleteCustomRoleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCustomRoleUnauthorized creates a DeleteCustomRoleUnauthorized with default headers values
func NewDeleteCustomRoleUnauthorized() *DeleteCustomRoleUnauthorized {
	return &DeleteCustomRoleUnauthorized{}
}

/*DeleteCustomRoleUnauthorized handles this case with default header values.

Invalid access token.
*/
type DeleteCustomRoleUnauthorized struct {
}

func (o *DeleteCustomRoleUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /roles/{customRoleKey}][%d] deleteCustomRoleUnauthorized ", 401)
}

func (o *DeleteCustomRoleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCustomRoleNotFound creates a DeleteCustomRoleNotFound with default headers values
func NewDeleteCustomRoleNotFound() *DeleteCustomRoleNotFound {
	return &DeleteCustomRoleNotFound{}
}

/*DeleteCustomRoleNotFound handles this case with default header values.

Invalid resource specifier.
*/
type DeleteCustomRoleNotFound struct {
}

func (o *DeleteCustomRoleNotFound) Error() string {
	return fmt.Sprintf("[DELETE /roles/{customRoleKey}][%d] deleteCustomRoleNotFound ", 404)
}

func (o *DeleteCustomRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
