// Code generated by go-swagger; DO NOT EDIT.

package custom_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCustomRolesParams creates a new GetCustomRolesParams object
// with the default values initialized.
func NewGetCustomRolesParams() *GetCustomRolesParams {

	return &GetCustomRolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomRolesParamsWithTimeout creates a new GetCustomRolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCustomRolesParamsWithTimeout(timeout time.Duration) *GetCustomRolesParams {

	return &GetCustomRolesParams{

		timeout: timeout,
	}
}

// NewGetCustomRolesParamsWithContext creates a new GetCustomRolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCustomRolesParamsWithContext(ctx context.Context) *GetCustomRolesParams {

	return &GetCustomRolesParams{

		Context: ctx,
	}
}

// NewGetCustomRolesParamsWithHTTPClient creates a new GetCustomRolesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCustomRolesParamsWithHTTPClient(client *http.Client) *GetCustomRolesParams {

	return &GetCustomRolesParams{
		HTTPClient: client,
	}
}

/*GetCustomRolesParams contains all the parameters to send to the API endpoint
for the get custom roles operation typically these are written to a http.Request
*/
type GetCustomRolesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get custom roles params
func (o *GetCustomRolesParams) WithTimeout(timeout time.Duration) *GetCustomRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get custom roles params
func (o *GetCustomRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get custom roles params
func (o *GetCustomRolesParams) WithContext(ctx context.Context) *GetCustomRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get custom roles params
func (o *GetCustomRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get custom roles params
func (o *GetCustomRolesParams) WithHTTPClient(client *http.Client) *GetCustomRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get custom roles params
func (o *GetCustomRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
