// Code generated by go-swagger; DO NOT EDIT.

package custom_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCustomRoleParams creates a new GetCustomRoleParams object
// with the default values initialized.
func NewGetCustomRoleParams() *GetCustomRoleParams {
	var ()
	return &GetCustomRoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomRoleParamsWithTimeout creates a new GetCustomRoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCustomRoleParamsWithTimeout(timeout time.Duration) *GetCustomRoleParams {
	var ()
	return &GetCustomRoleParams{

		timeout: timeout,
	}
}

// NewGetCustomRoleParamsWithContext creates a new GetCustomRoleParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCustomRoleParamsWithContext(ctx context.Context) *GetCustomRoleParams {
	var ()
	return &GetCustomRoleParams{

		Context: ctx,
	}
}

// NewGetCustomRoleParamsWithHTTPClient creates a new GetCustomRoleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCustomRoleParamsWithHTTPClient(client *http.Client) *GetCustomRoleParams {
	var ()
	return &GetCustomRoleParams{
		HTTPClient: client,
	}
}

/*GetCustomRoleParams contains all the parameters to send to the API endpoint
for the get custom role operation typically these are written to a http.Request
*/
type GetCustomRoleParams struct {

	/*CustomRoleKey
	  The custom role key.

	*/
	CustomRoleKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get custom role params
func (o *GetCustomRoleParams) WithTimeout(timeout time.Duration) *GetCustomRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get custom role params
func (o *GetCustomRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get custom role params
func (o *GetCustomRoleParams) WithContext(ctx context.Context) *GetCustomRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get custom role params
func (o *GetCustomRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get custom role params
func (o *GetCustomRoleParams) WithHTTPClient(client *http.Client) *GetCustomRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get custom role params
func (o *GetCustomRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomRoleKey adds the customRoleKey to the get custom role params
func (o *GetCustomRoleParams) WithCustomRoleKey(customRoleKey string) *GetCustomRoleParams {
	o.SetCustomRoleKey(customRoleKey)
	return o
}

// SetCustomRoleKey adds the customRoleKey to the get custom role params
func (o *GetCustomRoleParams) SetCustomRoleKey(customRoleKey string) {
	o.CustomRoleKey = customRoleKey
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customRoleKey
	if err := r.SetPathParam("customRoleKey", o.CustomRoleKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
