// Code generated by go-swagger; DO NOT EDIT.

package custom_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/launchdarkly-api-client/models"
)

// NewPatchCustomRoleParams creates a new PatchCustomRoleParams object
// with the default values initialized.
func NewPatchCustomRoleParams() *PatchCustomRoleParams {
	var ()
	return &PatchCustomRoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchCustomRoleParamsWithTimeout creates a new PatchCustomRoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchCustomRoleParamsWithTimeout(timeout time.Duration) *PatchCustomRoleParams {
	var ()
	return &PatchCustomRoleParams{

		timeout: timeout,
	}
}

// NewPatchCustomRoleParamsWithContext creates a new PatchCustomRoleParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchCustomRoleParamsWithContext(ctx context.Context) *PatchCustomRoleParams {
	var ()
	return &PatchCustomRoleParams{

		Context: ctx,
	}
}

// NewPatchCustomRoleParamsWithHTTPClient creates a new PatchCustomRoleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchCustomRoleParamsWithHTTPClient(client *http.Client) *PatchCustomRoleParams {
	var ()
	return &PatchCustomRoleParams{
		HTTPClient: client,
	}
}

/*PatchCustomRoleParams contains all the parameters to send to the API endpoint
for the patch custom role operation typically these are written to a http.Request
*/
type PatchCustomRoleParams struct {

	/*CustomRoleKey
	  The custom role key.

	*/
	CustomRoleKey string
	/*PatchDelta
	  Requires a JSON Patch representation of the desired changes to the project. 'http://jsonpatch.com/'

	*/
	PatchDelta []*models.PatchOperation

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch custom role params
func (o *PatchCustomRoleParams) WithTimeout(timeout time.Duration) *PatchCustomRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch custom role params
func (o *PatchCustomRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch custom role params
func (o *PatchCustomRoleParams) WithContext(ctx context.Context) *PatchCustomRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch custom role params
func (o *PatchCustomRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch custom role params
func (o *PatchCustomRoleParams) WithHTTPClient(client *http.Client) *PatchCustomRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch custom role params
func (o *PatchCustomRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomRoleKey adds the customRoleKey to the patch custom role params
func (o *PatchCustomRoleParams) WithCustomRoleKey(customRoleKey string) *PatchCustomRoleParams {
	o.SetCustomRoleKey(customRoleKey)
	return o
}

// SetCustomRoleKey adds the customRoleKey to the patch custom role params
func (o *PatchCustomRoleParams) SetCustomRoleKey(customRoleKey string) {
	o.CustomRoleKey = customRoleKey
}

// WithPatchDelta adds the patchDelta to the patch custom role params
func (o *PatchCustomRoleParams) WithPatchDelta(patchDelta []*models.PatchOperation) *PatchCustomRoleParams {
	o.SetPatchDelta(patchDelta)
	return o
}

// SetPatchDelta adds the patchDelta to the patch custom role params
func (o *PatchCustomRoleParams) SetPatchDelta(patchDelta []*models.PatchOperation) {
	o.PatchDelta = patchDelta
}

// WriteToRequest writes these params to a swagger request
func (o *PatchCustomRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customRoleKey
	if err := r.SetPathParam("customRoleKey", o.CustomRoleKey); err != nil {
		return err
	}

	if o.PatchDelta != nil {
		if err := r.SetBodyParam(o.PatchDelta); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
