// Code generated by go-swagger; DO NOT EDIT.

package custom_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/go-launchdarkly/models"
)

// PostCustomRoleReader is a Reader for the PostCustomRole structure.
type PostCustomRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostCustomRoleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostCustomRoleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostCustomRoleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewPostCustomRoleConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostCustomRoleCreated creates a PostCustomRoleCreated with default headers values
func NewPostCustomRoleCreated() *PostCustomRoleCreated {
	return &PostCustomRoleCreated{}
}

/*PostCustomRoleCreated handles this case with default header values.

Resource created.
*/
type PostCustomRoleCreated struct {
}

func (o *PostCustomRoleCreated) Error() string {
	return fmt.Sprintf("[POST /roles][%d] postCustomRoleCreated ", 201)
}

func (o *PostCustomRoleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomRoleBadRequest creates a PostCustomRoleBadRequest with default headers values
func NewPostCustomRoleBadRequest() *PostCustomRoleBadRequest {
	return &PostCustomRoleBadRequest{}
}

/*PostCustomRoleBadRequest handles this case with default header values.

Invalid request body.
*/
type PostCustomRoleBadRequest struct {
}

func (o *PostCustomRoleBadRequest) Error() string {
	return fmt.Sprintf("[POST /roles][%d] postCustomRoleBadRequest ", 400)
}

func (o *PostCustomRoleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomRoleUnauthorized creates a PostCustomRoleUnauthorized with default headers values
func NewPostCustomRoleUnauthorized() *PostCustomRoleUnauthorized {
	return &PostCustomRoleUnauthorized{}
}

/*PostCustomRoleUnauthorized handles this case with default header values.

Invalid access token.
*/
type PostCustomRoleUnauthorized struct {
}

func (o *PostCustomRoleUnauthorized) Error() string {
	return fmt.Sprintf("[POST /roles][%d] postCustomRoleUnauthorized ", 401)
}

func (o *PostCustomRoleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomRoleConflict creates a PostCustomRoleConflict with default headers values
func NewPostCustomRoleConflict() *PostCustomRoleConflict {
	return &PostCustomRoleConflict{}
}

/*PostCustomRoleConflict handles this case with default header values.

Status conflict.
*/
type PostCustomRoleConflict struct {
}

func (o *PostCustomRoleConflict) Error() string {
	return fmt.Sprintf("[POST /roles][%d] postCustomRoleConflict ", 409)
}

func (o *PostCustomRoleConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PostCustomRoleBody post custom role body
swagger:model PostCustomRoleBody
*/
type PostCustomRoleBody struct {

	// Description of the custom role.
	Description string `json:"description,omitempty"`

	// key
	// Required: true
	Key models.CustomRoleKeyOrID `json:"key"`

	// Name of the custom role.
	// Required: true
	Name *string `json:"name"`

	// policy
	// Required: true
	Policy []*models.Policy `json:"policy"`
}

// Validate validates this post custom role body
func (o *PostCustomRoleBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCustomRoleBody) validateKey(formats strfmt.Registry) error {

	if err := o.Key.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("customRoleBody" + "." + "key")
		}
		return err
	}

	return nil
}

func (o *PostCustomRoleBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("customRoleBody"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

func (o *PostCustomRoleBody) validatePolicy(formats strfmt.Registry) error {

	if err := validate.Required("customRoleBody"+"."+"policy", "body", o.Policy); err != nil {
		return err
	}

	for i := 0; i < len(o.Policy); i++ {
		if swag.IsZero(o.Policy[i]) { // not required
			continue
		}

		if o.Policy[i] != nil {
			if err := o.Policy[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("customRoleBody" + "." + "policy" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostCustomRoleBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostCustomRoleBody) UnmarshalBinary(b []byte) error {
	var res PostCustomRoleBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
