// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteEnvironmentReader is a Reader for the DeleteEnvironment structure.
type DeleteEnvironmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteEnvironmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteEnvironmentNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteEnvironmentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteEnvironmentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteEnvironmentNoContent creates a DeleteEnvironmentNoContent with default headers values
func NewDeleteEnvironmentNoContent() *DeleteEnvironmentNoContent {
	return &DeleteEnvironmentNoContent{}
}

/*DeleteEnvironmentNoContent handles this case with default header values.

Action completed successfully.
*/
type DeleteEnvironmentNoContent struct {
}

func (o *DeleteEnvironmentNoContent) Error() string {
	return fmt.Sprintf("[DELETE /projects/{projectKey}/environments/{environmentKey}][%d] deleteEnvironmentNoContent ", 204)
}

func (o *DeleteEnvironmentNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteEnvironmentUnauthorized creates a DeleteEnvironmentUnauthorized with default headers values
func NewDeleteEnvironmentUnauthorized() *DeleteEnvironmentUnauthorized {
	return &DeleteEnvironmentUnauthorized{}
}

/*DeleteEnvironmentUnauthorized handles this case with default header values.

Invalid access token.
*/
type DeleteEnvironmentUnauthorized struct {
}

func (o *DeleteEnvironmentUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /projects/{projectKey}/environments/{environmentKey}][%d] deleteEnvironmentUnauthorized ", 401)
}

func (o *DeleteEnvironmentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteEnvironmentNotFound creates a DeleteEnvironmentNotFound with default headers values
func NewDeleteEnvironmentNotFound() *DeleteEnvironmentNotFound {
	return &DeleteEnvironmentNotFound{}
}

/*DeleteEnvironmentNotFound handles this case with default header values.

Invalid resource specifier.
*/
type DeleteEnvironmentNotFound struct {
}

func (o *DeleteEnvironmentNotFound) Error() string {
	return fmt.Sprintf("[DELETE /projects/{projectKey}/environments/{environmentKey}][%d] deleteEnvironmentNotFound ", 404)
}

func (o *DeleteEnvironmentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
