// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteEnvironmentParams creates a new DeleteEnvironmentParams object
// with the default values initialized.
func NewDeleteEnvironmentParams() *DeleteEnvironmentParams {
	var ()
	return &DeleteEnvironmentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEnvironmentParamsWithTimeout creates a new DeleteEnvironmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteEnvironmentParamsWithTimeout(timeout time.Duration) *DeleteEnvironmentParams {
	var ()
	return &DeleteEnvironmentParams{

		timeout: timeout,
	}
}

// NewDeleteEnvironmentParamsWithContext creates a new DeleteEnvironmentParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteEnvironmentParamsWithContext(ctx context.Context) *DeleteEnvironmentParams {
	var ()
	return &DeleteEnvironmentParams{

		Context: ctx,
	}
}

// NewDeleteEnvironmentParamsWithHTTPClient creates a new DeleteEnvironmentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteEnvironmentParamsWithHTTPClient(client *http.Client) *DeleteEnvironmentParams {
	var ()
	return &DeleteEnvironmentParams{
		HTTPClient: client,
	}
}

/*DeleteEnvironmentParams contains all the parameters to send to the API endpoint
for the delete environment operation typically these are written to a http.Request
*/
type DeleteEnvironmentParams struct {

	/*EnvironmentKey
	  The environment key, used to tie together flag configuration and users under one environment so they can be managed together.

	*/
	EnvironmentKey string
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete environment params
func (o *DeleteEnvironmentParams) WithTimeout(timeout time.Duration) *DeleteEnvironmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete environment params
func (o *DeleteEnvironmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete environment params
func (o *DeleteEnvironmentParams) WithContext(ctx context.Context) *DeleteEnvironmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete environment params
func (o *DeleteEnvironmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete environment params
func (o *DeleteEnvironmentParams) WithHTTPClient(client *http.Client) *DeleteEnvironmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete environment params
func (o *DeleteEnvironmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentKey adds the environmentKey to the delete environment params
func (o *DeleteEnvironmentParams) WithEnvironmentKey(environmentKey string) *DeleteEnvironmentParams {
	o.SetEnvironmentKey(environmentKey)
	return o
}

// SetEnvironmentKey adds the environmentKey to the delete environment params
func (o *DeleteEnvironmentParams) SetEnvironmentKey(environmentKey string) {
	o.EnvironmentKey = environmentKey
}

// WithProjectKey adds the projectKey to the delete environment params
func (o *DeleteEnvironmentParams) WithProjectKey(projectKey string) *DeleteEnvironmentParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the delete environment params
func (o *DeleteEnvironmentParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEnvironmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentKey
	if err := r.SetPathParam("environmentKey", o.EnvironmentKey); err != nil {
		return err
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
