// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/go-launchdarkly/models"
)

// NewPatchEnvironmentParams creates a new PatchEnvironmentParams object
// with the default values initialized.
func NewPatchEnvironmentParams() *PatchEnvironmentParams {
	var ()
	return &PatchEnvironmentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchEnvironmentParamsWithTimeout creates a new PatchEnvironmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchEnvironmentParamsWithTimeout(timeout time.Duration) *PatchEnvironmentParams {
	var ()
	return &PatchEnvironmentParams{

		timeout: timeout,
	}
}

// NewPatchEnvironmentParamsWithContext creates a new PatchEnvironmentParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchEnvironmentParamsWithContext(ctx context.Context) *PatchEnvironmentParams {
	var ()
	return &PatchEnvironmentParams{

		Context: ctx,
	}
}

// NewPatchEnvironmentParamsWithHTTPClient creates a new PatchEnvironmentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchEnvironmentParamsWithHTTPClient(client *http.Client) *PatchEnvironmentParams {
	var ()
	return &PatchEnvironmentParams{
		HTTPClient: client,
	}
}

/*PatchEnvironmentParams contains all the parameters to send to the API endpoint
for the patch environment operation typically these are written to a http.Request
*/
type PatchEnvironmentParams struct {

	/*EnvironmentKey
	  The environment key, used to tie together flag configuration and users under one environment so they can be managed together.

	*/
	EnvironmentKey string
	/*PatchDelta
	  Requires a JSON Patch representation of the desired changes to the project. 'http://jsonpatch.com/'

	*/
	PatchDelta []*models.PatchOperation
	/*ProjectKey
	  The project key, used to tie the flags together under one project so they can be managed together.

	*/
	ProjectKey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch environment params
func (o *PatchEnvironmentParams) WithTimeout(timeout time.Duration) *PatchEnvironmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch environment params
func (o *PatchEnvironmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch environment params
func (o *PatchEnvironmentParams) WithContext(ctx context.Context) *PatchEnvironmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch environment params
func (o *PatchEnvironmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch environment params
func (o *PatchEnvironmentParams) WithHTTPClient(client *http.Client) *PatchEnvironmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch environment params
func (o *PatchEnvironmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentKey adds the environmentKey to the patch environment params
func (o *PatchEnvironmentParams) WithEnvironmentKey(environmentKey string) *PatchEnvironmentParams {
	o.SetEnvironmentKey(environmentKey)
	return o
}

// SetEnvironmentKey adds the environmentKey to the patch environment params
func (o *PatchEnvironmentParams) SetEnvironmentKey(environmentKey string) {
	o.EnvironmentKey = environmentKey
}

// WithPatchDelta adds the patchDelta to the patch environment params
func (o *PatchEnvironmentParams) WithPatchDelta(patchDelta []*models.PatchOperation) *PatchEnvironmentParams {
	o.SetPatchDelta(patchDelta)
	return o
}

// SetPatchDelta adds the patchDelta to the patch environment params
func (o *PatchEnvironmentParams) SetPatchDelta(patchDelta []*models.PatchOperation) {
	o.PatchDelta = patchDelta
}

// WithProjectKey adds the projectKey to the patch environment params
func (o *PatchEnvironmentParams) WithProjectKey(projectKey string) *PatchEnvironmentParams {
	o.SetProjectKey(projectKey)
	return o
}

// SetProjectKey adds the projectKey to the patch environment params
func (o *PatchEnvironmentParams) SetProjectKey(projectKey string) {
	o.ProjectKey = projectKey
}

// WriteToRequest writes these params to a swagger request
func (o *PatchEnvironmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentKey
	if err := r.SetPathParam("environmentKey", o.EnvironmentKey); err != nil {
		return err
	}

	if o.PatchDelta != nil {
		if err := r.SetBodyParam(o.PatchDelta); err != nil {
			return err
		}
	}

	// path param projectKey
	if err := r.SetPathParam("projectKey", o.ProjectKey); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
