// Code generated by go-swagger; DO NOT EDIT.

package team_members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteMemberReader is a Reader for the DeleteMember structure.
type DeleteMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteMemberNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteMemberUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteMemberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteMemberNoContent creates a DeleteMemberNoContent with default headers values
func NewDeleteMemberNoContent() *DeleteMemberNoContent {
	return &DeleteMemberNoContent{}
}

/*DeleteMemberNoContent handles this case with default header values.

Action completed successfully.
*/
type DeleteMemberNoContent struct {
}

func (o *DeleteMemberNoContent) Error() string {
	return fmt.Sprintf("[DELETE /members/{memberId}][%d] deleteMemberNoContent ", 204)
}

func (o *DeleteMemberNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMemberUnauthorized creates a DeleteMemberUnauthorized with default headers values
func NewDeleteMemberUnauthorized() *DeleteMemberUnauthorized {
	return &DeleteMemberUnauthorized{}
}

/*DeleteMemberUnauthorized handles this case with default header values.

Invalid access token.
*/
type DeleteMemberUnauthorized struct {
}

func (o *DeleteMemberUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /members/{memberId}][%d] deleteMemberUnauthorized ", 401)
}

func (o *DeleteMemberUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMemberNotFound creates a DeleteMemberNotFound with default headers values
func NewDeleteMemberNotFound() *DeleteMemberNotFound {
	return &DeleteMemberNotFound{}
}

/*DeleteMemberNotFound handles this case with default header values.

Invalid resource specifier.
*/
type DeleteMemberNotFound struct {
}

func (o *DeleteMemberNotFound) Error() string {
	return fmt.Sprintf("[DELETE /members/{memberId}][%d] deleteMemberNotFound ", 404)
}

func (o *DeleteMemberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
