// Code generated by go-swagger; DO NOT EDIT.

package team_members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/launchdarkly-api-client/models"
)

// GetMemberReader is a Reader for the GetMember structure.
type GetMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMemberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetMemberBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetMemberUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMemberOK creates a GetMemberOK with default headers values
func NewGetMemberOK() *GetMemberOK {
	return &GetMemberOK{}
}

/*GetMemberOK handles this case with default header values.

Member response.
*/
type GetMemberOK struct {
	Payload *models.Member
}

func (o *GetMemberOK) Error() string {
	return fmt.Sprintf("[GET /members/{memberId}][%d] getMemberOK  %+v", 200, o.Payload)
}

func (o *GetMemberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Member)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMemberBadRequest creates a GetMemberBadRequest with default headers values
func NewGetMemberBadRequest() *GetMemberBadRequest {
	return &GetMemberBadRequest{}
}

/*GetMemberBadRequest handles this case with default header values.

Invalid request body.
*/
type GetMemberBadRequest struct {
}

func (o *GetMemberBadRequest) Error() string {
	return fmt.Sprintf("[GET /members/{memberId}][%d] getMemberBadRequest ", 400)
}

func (o *GetMemberBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMemberUnauthorized creates a GetMemberUnauthorized with default headers values
func NewGetMemberUnauthorized() *GetMemberUnauthorized {
	return &GetMemberUnauthorized{}
}

/*GetMemberUnauthorized handles this case with default header values.

Invalid access token.
*/
type GetMemberUnauthorized struct {
}

func (o *GetMemberUnauthorized) Error() string {
	return fmt.Sprintf("[GET /members/{memberId}][%d] getMemberUnauthorized ", 401)
}

func (o *GetMemberUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
