// Code generated by go-swagger; DO NOT EDIT.

package team_members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mlafeldt/launchdarkly-api-client/models"
)

// PostMembersReader is a Reader for the PostMembers structure.
type PostMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostMembersCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostMembersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostMembersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewPostMembersConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMembersCreated creates a PostMembersCreated with default headers values
func NewPostMembersCreated() *PostMembersCreated {
	return &PostMembersCreated{}
}

/*PostMembersCreated handles this case with default header values.

Resource created.
*/
type PostMembersCreated struct {
}

func (o *PostMembersCreated) Error() string {
	return fmt.Sprintf("[POST /members][%d] postMembersCreated ", 201)
}

func (o *PostMembersCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostMembersBadRequest creates a PostMembersBadRequest with default headers values
func NewPostMembersBadRequest() *PostMembersBadRequest {
	return &PostMembersBadRequest{}
}

/*PostMembersBadRequest handles this case with default header values.

Invalid request body.
*/
type PostMembersBadRequest struct {
}

func (o *PostMembersBadRequest) Error() string {
	return fmt.Sprintf("[POST /members][%d] postMembersBadRequest ", 400)
}

func (o *PostMembersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostMembersUnauthorized creates a PostMembersUnauthorized with default headers values
func NewPostMembersUnauthorized() *PostMembersUnauthorized {
	return &PostMembersUnauthorized{}
}

/*PostMembersUnauthorized handles this case with default header values.

Invalid access token.
*/
type PostMembersUnauthorized struct {
}

func (o *PostMembersUnauthorized) Error() string {
	return fmt.Sprintf("[POST /members][%d] postMembersUnauthorized ", 401)
}

func (o *PostMembersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostMembersConflict creates a PostMembersConflict with default headers values
func NewPostMembersConflict() *PostMembersConflict {
	return &PostMembersConflict{}
}

/*PostMembersConflict handles this case with default header values.

Status conflict.
*/
type PostMembersConflict struct {
}

func (o *PostMembersConflict) Error() string {
	return fmt.Sprintf("[POST /members][%d] postMembersConflict ", 409)
}

func (o *PostMembersConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PostMembersParamsBodyItems0 post members params body items0
swagger:model PostMembersParamsBodyItems0
*/
type PostMembersParamsBodyItems0 struct {

	// custom roles
	CustomRoles []models.CustomRoleKeyOrID `json:"customRoles"`

	// email
	// Required: true
	Email *string `json:"email"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// inline role
	InlineRole models.Statements `json:"inlineRole"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// role
	Role models.Role `json:"role,omitempty"`
}

// Validate validates this post members params body items0
func (o *PostMembersParamsBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCustomRoles(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateInlineRole(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostMembersParamsBodyItems0) validateCustomRoles(formats strfmt.Registry) error {

	if swag.IsZero(o.CustomRoles) { // not required
		return nil
	}

	for i := 0; i < len(o.CustomRoles); i++ {

		if err := o.CustomRoles[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("customRoles" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (o *PostMembersParamsBodyItems0) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", o.Email); err != nil {
		return err
	}

	return nil
}

func (o *PostMembersParamsBodyItems0) validateInlineRole(formats strfmt.Registry) error {

	if swag.IsZero(o.InlineRole) { // not required
		return nil
	}

	if err := o.InlineRole.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("inlineRole")
		}
		return err
	}

	return nil
}

func (o *PostMembersParamsBodyItems0) validateRole(formats strfmt.Registry) error {

	if swag.IsZero(o.Role) { // not required
		return nil
	}

	if err := o.Role.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("role")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostMembersParamsBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostMembersParamsBodyItems0) UnmarshalBinary(b []byte) error {
	var res PostMembersParamsBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
