// Code generated by go-swagger; DO NOT EDIT.

package audit_log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAuditLogEntryParams creates a new GetAuditLogEntryParams object
// with the default values initialized.
func NewGetAuditLogEntryParams() *GetAuditLogEntryParams {
	var ()
	return &GetAuditLogEntryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuditLogEntryParamsWithTimeout creates a new GetAuditLogEntryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuditLogEntryParamsWithTimeout(timeout time.Duration) *GetAuditLogEntryParams {
	var ()
	return &GetAuditLogEntryParams{

		timeout: timeout,
	}
}

// NewGetAuditLogEntryParamsWithContext creates a new GetAuditLogEntryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuditLogEntryParamsWithContext(ctx context.Context) *GetAuditLogEntryParams {
	var ()
	return &GetAuditLogEntryParams{

		Context: ctx,
	}
}

// NewGetAuditLogEntryParamsWithHTTPClient creates a new GetAuditLogEntryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuditLogEntryParamsWithHTTPClient(client *http.Client) *GetAuditLogEntryParams {
	var ()
	return &GetAuditLogEntryParams{
		HTTPClient: client,
	}
}

/*GetAuditLogEntryParams contains all the parameters to send to the API endpoint
for the get audit log entry operation typically these are written to a http.Request
*/
type GetAuditLogEntryParams struct {

	/*ResourceID
	  The resource ID.

	*/
	ResourceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get audit log entry params
func (o *GetAuditLogEntryParams) WithTimeout(timeout time.Duration) *GetAuditLogEntryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get audit log entry params
func (o *GetAuditLogEntryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get audit log entry params
func (o *GetAuditLogEntryParams) WithContext(ctx context.Context) *GetAuditLogEntryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get audit log entry params
func (o *GetAuditLogEntryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get audit log entry params
func (o *GetAuditLogEntryParams) WithHTTPClient(client *http.Client) *GetAuditLogEntryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get audit log entry params
func (o *GetAuditLogEntryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the get audit log entry params
func (o *GetAuditLogEntryParams) WithResourceID(resourceID string) *GetAuditLogEntryParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the get audit log entry params
func (o *GetAuditLogEntryParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuditLogEntryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
