// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Action An action to perform on a resource.
// swagger:model Action
type Action string

// Validate validates this action
func (m Action) Validate(formats strfmt.Registry) error {
	return nil
}
