// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// CustomPropertyValues Values for this property.
// swagger:model CustomPropertyValues
type CustomPropertyValues []string

// Validate validates this custom property values
func (m CustomPropertyValues) Validate(formats strfmt.Registry) error {
	return nil
}
