// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// CustomRoleKeyOrID The 20-hexdigit id or the key for a custom role.
// swagger:model CustomRoleKeyOrId
type CustomRoleKeyOrID string

// Validate validates this custom role key or Id
func (m CustomRoleKeyOrID) Validate(formats strfmt.Registry) error {
	return nil
}
