// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ID The unique resource id.
// swagger:model Id
type ID string

// Validate validates this Id
func (m ID) Validate(formats strfmt.Registry) error {
	return nil
}
