// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Prerequisite prerequisite
// swagger:model Prerequisite
type Prerequisite struct {

	// key
	Key string `json:"key,omitempty"`

	// variation
	Variation int64 `json:"variation,omitempty"`
}

// Validate validates this prerequisite
func (m *Prerequisite) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Prerequisite) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Prerequisite) UnmarshalBinary(b []byte) error {
	var res Prerequisite
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
