// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Role role
// swagger:model Role
type Role string

const (

	// RoleWriter captures enum value "writer"
	RoleWriter Role = "writer"

	// RoleReader captures enum value "reader"
	RoleReader Role = "reader"

	// RoleAdmin captures enum value "admin"
	RoleAdmin Role = "admin"

	// RoleOwner captures enum value "owner"
	RoleOwner Role = "owner"
)

// for schema
var roleEnum []interface{}

func init() {
	var res []Role
	if err := json.Unmarshal([]byte(`["writer","reader","admin","owner"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		roleEnum = append(roleEnum, v)
	}
}

func (m Role) validateRoleEnum(path, location string, value Role) error {
	if err := validate.Enum(path, location, value, roleEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this role
func (m Role) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateRoleEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
