// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WeightedVariation weighted variation
// swagger:model WeightedVariation
type WeightedVariation struct {

	// variation
	Variation int64 `json:"variation,omitempty"`

	// weight
	Weight int64 `json:"weight,omitempty"`
}

// Validate validates this weighted variation
func (m *WeightedVariation) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WeightedVariation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WeightedVariation) UnmarshalBinary(b []byte) error {
	var res WeightedVariation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
